version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ethan
      POSTGRES_PASSWORD: ethan
      POSTGRES_DB: databasebos
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: